Chapter: Add missing include
Fixes a compilation error on gcc 13.2:

> In file included from ../src/Chapter.h:25,
>                  from ../src/Chapter.cpp:27:
>../include/medialibrary/IChapter.h:42:13: error: 'int64_t' does not name a type
>   42 |     virtual int64_t offset() const = 0;